#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 12 13:41:10 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 7912c2749ff043e790b2d3d3e38c2540 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Rx_Top_TB_behav xil_defaultlib.Rx_Top_TB xil_defaultlib.glbl -log elaborate.log"
xelab -wto 7912c2749ff043e790b2d3d3e38c2540 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Rx_Top_TB_behav xil_defaultlib.Rx_Top_TB xil_defaultlib.glbl -log elaborate.log

